CREATE TYPE "TimeClockDeviceType" AS ENUM ('FIXED', 'MOBILE');

ALTER TABLE "Branch"
ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "geofenceRadiusMeters" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "TimeClockEntry"
ADD COLUMN "deviceType" "TimeClockDeviceType" NOT NULL DEFAULT 'FIXED',
ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "accuracy" DOUBLE PRECISION,
ADD COLUMN "isWithinRadius" BOOLEAN,
ADD COLUMN "distanceFromBranch" DOUBLE PRECISION;
